#!/bin/sh

set -e

lb config noauto \
	--apt-indices true \
	--apt-recommends false \
	--architectures amd64 \
	--memtest none \
	--system live \
	--archive-areas "main contrib non-free" \
	--distribution buster \
	"${@}"

echo "terminator htop snapd zsh remmina" > config/package-lists/standard.list.chroot
