#!/bin/sh

set -e

lb config noauto \
	--apt-indices true \
	--apt-recommends false \
	--architectures amd64 \
	--memtest none \
	--system live \
	--archive-areas "main contrib non-free" \
	--distribution buster \
	"${@}"

cp -r auto/package-lists/* config/package-lists/

cp -r auto/hooks/live/* config/hooks/live/

cp -r auto/includes.chroot/* config/includes.chroot/

cp -r auto/bootloaders config
