#!/bin/sh

useradd -mG sudo -s /bin/zsh user

echo "user:p@ssw0rd" | chpasswd

touch /home/user/.zshrc

chown user:user /home/user/.config/Code/User/settings.json

runuser -l user -c 'setup-ohmyzsh --unattended'

