#!/bin/sh

useradd -mG sudo -s /bin/zsh user

echo "user:p@ssw0rd" | chpasswd

touch /home/user/.zshrc

mkdir -/home/user/.ssh

mkdir -p /home/user/.config/autostart

cp /usr/local/share/*.desktop /home/user/.config/autostart

chown -R user:user /home/user
